[Feature/#44] 동영상 리스트 UseCase 작성 + 동기화 로직
boostcampwm-2024/iOS09-BeStory pull request #57
Opened 2024-11-22 09:39 UTC by LURKS02

## 관련 이슈

- #44 
- #56

## ✅ 완료 및 수정 내역
- 의존성 등록
- UseCase 작성
- Repository 연동
- 동영상 동기화 로직 구현

## 🛠️ 테스트 방법
SocketProvider를 수정해서 기본적으로 통신이 가능한 상황에서 테스트 했습니다. (깜빡하고 테스트 코드를 올렸습니다. ㅜㅜ 기존 로직 복원하는 커밋 추가했습니다)<br>
동시에 synchronized 확인이 되었을 때 TempViewController를 present하는 방법으로 했고, 지금은 navigationController.push로 바꾸어 놓았습니다.

## 📝 리뷰 노트

동영상 업로드를 마친 상황에서 다음 버튼을 누르면 -> 피어들에게 해시 값을 비교하도록 요청 -> 해시 값에 대한 SyncMessage 리턴 -> SyncMessage 결과를 딕셔너리로 저장하여 모두 true일 경우 화면 전환 플래그 전송 + 화면 전환

현재는 이렇게 로직이 구현되어 있는데, 정상적인 경우만 테스트 하였고 예외 상황에 대한 처리는 작업 후 따로 PR을 만들어서 올려야 할 것 같습니다. (이 부분에서 시간이 많이 걸릴 것 같습니다.)<br>

고민되는 부분은 다음과 같습니다.
- SyncMessage는 어디에 위치해야 하는지?
- Core를 여기 저기서 사용하고 있는데 괜찮을지?

## 📱 스크린샷(선택)

https://github.com/user-attachments/assets/b9f73855-83de-4d5e-b8df-e1bc9c7d311f

2024-11-22 10:42 UTC, 051198Hz requested changes
아이고... session 델레게이트 메소드만 봐도 고생하신게 느껴지네요.
고생 많으셨습니다~!

2024-11-22 10:42 UTC, 051198Hz commented on Core/Utilities/FileSystemManager.swift
> +//  Created by 디해 on 11/15/24.
P3: 음....사소하지만 주석의 파일 명이랑 레이어 정도만 어떻게..부탁드립니다

2024-11-22 10:42 UTC, 051198Hz commented on Core/Utilities/FileSystemManager.swift
> +    }
P2: 아마 어떤 고민이 있으셔서 분리하셨을 것 같지만, 하나로 합칠 수 있을 것 같아요.
파라미터로 withName을 주고, 기본값을 nil로 준 다음 withName에 따라 originalFileName이 결정되도록 하는건 어떤가요?

2024-11-22 10:54 UTC, 051198Hz commented
- SyncMessage는 어디에 위치해야 하는지?
SyncMessage 자체는 SoketProvider에서 상위로 전달하는것에 문제 없다고 생각합니다.
그러나 Sync가 됐는지를 판단하는 작업은 Sync검사를 담당하는 객체를 만드는 것이 어떨까 합니다.
현재 딕셔너리, 메세지를 파싱하는 작접을 위임하고, 비교할 대상을 전달받고
외부에 SyncMessage나 Bool등을 반환하도록 하는 것은 어떤가요?
책임도 분리할 수 있고, 메서드 명 등으로 추상화 수준도 올릴 수 있을것이 기대됩니다.

Core를 여기 저기서 사용하고 있는데 괜찮을지?
다이죠부 하다는 의견입니다.

2024-11-25 15:33 UTC, jungseokyoung-cloud approved these changes
고생하셨습니다! 
다만, 동기화 관련 로직을 P2PSocket이 아닌 UseCase 혹은 Repository로 옮겨보는 것은 어떨까요? 
개인적으로 P2PSocket의 역할이 점점 많아지는 것 같아서요!

2024-11-25 15:33 UTC, jungseokyoung-cloud commented on Core/Utilities/FileSystemManager.swift
> +    }
P3: 합칠수도 있고, `copyToFileSystem(tempURL:)` 메서드에서  `copyToFileSystem(tempURL:resourceName)`메서드를 활용해보는 것도 좋을 거 같습니다.

2024-11-25 15:33 UTC, jungseokyoung-cloud commented on Core/Utilities/FileSystemManager.swift
> +    private let folderName: String = "videos"
P3: 정말 너무 사소한 거여서 무시하셔도 좋습니다! 개인적으로 enum으로 관리해보면 어떨까 싶습니다.

2024-11-25 15:33 UTC, jungseokyoung-cloud commented on Data/P2PSocket/SocketProvider.swift
> +    }
P3: hash관련과 동기화 관련을 각각 method로 분리해볼 수는 없을까요?

2024-11-25 15:33 UTC, jungseokyoung-cloud commented on Feature/Feature/VideoListView/VideoListViewController.swift
> +    private let videoManager = FileSystemManager.shared
P2: 네이밍도 변경하셔야 할꺼 같습니다!

2024-11-25 15:34 UTC, around-forest approved these changes
정말 고생 많으셨습니다!

- SyncMessage는 어디에 위치해야 하는지?
저도 윤회님 의견에 동의합니다. SyncMessage는 영상 동기화에만 사용되고 있는 반면 Socket은 이미 다양한 역할을 담당하고 있기 때문에 따로 빼서 Socket의 역할도 조금이나마 줄이고 추후 Socket을 분리할 때에도 용이하게 하면 좋을 듯 하네요!

- Core를 여기 저기서 사용하고 있는데 괜찮을지?
괜찮다고 생각합니다. 애초에 Core를 따로 프로젝트로 분리한 이유가 여기저기서 사용될 코드들을 빼서 사용하자!도 있다 생각합니다.

2024-11-26 01:39 UTC, 051198Hz approved these changes

2024-11-26 05:51 UTC, LURKS02 commented on Core/Utilities/FileSystemManager.swift
> +//  Created by 디해 on 11/15/24.
수정했습니다!

2024-11-26 05:51 UTC, LURKS02 commented on Core/Utilities/FileSystemManager.swift
> +    }
수정했습니다!

2024-11-26 05:53 UTC, LURKS02 commented on Core/Utilities/FileSystemManager.swift
> +    private let folderName: String = "videos"
아직 수정하지는 않았는데, enum으로 관리했을 때 이점을 알려주실 수 있을까요?!

2024-11-26 05:53 UTC, LURKS02 commented on Feature/Feature/VideoListView/VideoListViewController.swift
> +    private let videoManager = FileSystemManager.shared
수정했습니다!

2024-11-26 05:53 UTC, LURKS02 commented on Data/P2PSocket/SocketProvider.swift
> +    }
로직 수정 하면서 리팩토링 하겠습니다!

2024-11-26 05:57 UTC, merged