[Feature/#74] CRDT Socket에 연결 및 UseCase
boostcampwm-2024/iOS09-BeStory pull request #84
Opened 2024-12-03 16:08 UTC by jungseokyoung-cloud

## 관련 이슈

- #74 

## ✅ 완료 및 수정 내역

- CRDT 소켓에 연결
- UseCase 연결 
- resourceOwner URL을 통해 받을 수 있도록 수정

### 작성 중

2024-12-03 22:38 UTC, around-forest approved these changes
고생하셨습니다! 
이 코드를 가지고 ViewModel 작업을 했던터라 approve 합니다!
리뷰는 새벽에 잠깐 한거라 다시 시간내서 한번 더 보고 추가할 거 있으면 하겠습니다!

2024-12-03 22:38 UTC, around-forest commented on Data/P2PSocket/SocketProvider.swift
> +        print(url.author())
P2: Print문이 남아있네요!

2024-12-03 22:38 UTC, around-forest commented on Domain/Entity/Video.swift
> +    public let endTime: Double
P2: startTime, endTime, index는 수정 가능해야 하지 않나요?

2024-12-03 22:38 UTC, around-forest commented on Domain/Interfaces/UseCaseInterface/VideoUseCaseInterface.swift
P3: VideoUseCase에서 역할에 따라 protocol로 구분해서 interface를 제공하는데, 그럼 EditVideoUseCase 처럼 VideoUseCaseInterface가 아닌 SharingVideoUseCaseInterface가 더 알맞지 않나 하는 생각이 드는데... 다른 분들 생각도 궁금하네요!

2024-12-04 00:28 UTC, jungseokyoung-cloud commented on Data/P2PSocket/SocketProvider.swift
> +        print(url.author())
반영했습니다!

2024-12-04 00:29 UTC, jungseokyoung-cloud commented on Domain/Interfaces/UseCaseInterface/VideoUseCaseInterface.swift
이건 확실히 수정이 필요해보이네요 EditVideo인데 다른 곳은 Video이긴 하네요!
다른 분들 동의 하시면 수정하겠습니다!

2024-12-04 00:30 UTC, jungseokyoung-cloud commented on Domain/Entity/Video.swift
> +    public let endTime: Double
제가 생각했던 흐름은 어차피 PresentationModel로 변활될꺼기 떄문에, 변경되고 다시 Video로 매핑되는 흐름을 생각했습니다. 
만약 현재 수정가능해야 하는 형태라고 생각하면 변경하겠습니다!

2024-12-04 01:24 UTC, around-forest commented on Domain/Entity/Video.swift
> +    public let endTime: Double
일단 현재 제가 석영님 코드 기반으로 구현한 코드에서는 ViewModel에서 [Video]로 원본? 을 저장하고 필요에 따라 PresentationModel 또는 TimelineItem으로 변환해서 전달하기는 합니다. 이때 Slider 편집에 적용도 기본적으로는 Video Entity로 이루어지고 있기는 합니다! 아직 제 코드도 확정은 아니기 때문에 리뷰 보면서 다른 분들 의견도 들어보면 좋을 듯 하네요

2024-12-04 02:05 UTC, 051198Hz requested changes
고생 많으셨습니다~

2024-12-04 02:05 UTC, 051198Hz commented on Domain/Entity/Video.swift
> +    public let endTime: Double
이건 뷰모델에서 어떻게 저장하고 있냐에 따라 다를 것 같네요
뷰모델에서도 같은 타입을 사용하고 있다면 바꿀 수 있는게 좋을 것 같아요.
그렇지 않으면 보일러 플레이팅이 생길 것 같네요

2024-12-04 02:05 UTC, 051198Hz commented on Data/Data/EditVideoRepository.swift
> +        await crdt.merge(with: elementSet)
P1: 스스로 에딧한걸 스스로 머지하고 있어서 . 이코드는 빠져야할것 같아요!
문제가 발생할 수 있어보이네요. 스스로에 대한 벡터클락이 올라갈거에요

2024-12-04 02:05 UTC, 051198Hz commented on Domain/UseCase/VideoUseCase.swift
> +    private let editVideoRepository: EditVideoRepositoryInterface
P1: 비디오 유즈케이스는 비디오 공유 화면에 쓰이는 유즈케이스인걸로 알고있는데 편집된 정보를 전달하는 레포지토리가 여기서 왜 필요한가요??

2024-12-04 02:05 UTC, 051198Hz commented on Domain/UseCase/VideoUseCase.swift
> +            .store(in: &cancellables)
P1: 비디오 공유 화면인데 트리밍과 재배열 등의 코드가 있어요. 불필요하지 않나요??

2024-12-04 02:05 UTC, 051198Hz commented on Domain/Interfaces/UseCaseInterface/VideoUseCaseInterface.swift
같은 생각입니다~

2024-12-04 02:05 UTC, 051198Hz commented on Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
> +    var reArrangingVideo: PassthroughSubject<[Video], Never> { get }
P1: 외부에서 어떻게 편집했는지는 상관 없이 업데이트된 비디오 배열만을 반환하는것은 어떤가요

2024-12-04 02:05 UTC, 051198Hz commented on Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
> +    func reArrangingVideo(_ video: Video)
P2: 이미 편집된 비디오만 받고있는데, 단순히 싱크홀로만 보여요.
순서 변경이나 비디오 트리밍 관련 로직이 여기에 있어야 하지 않을까요?

2024-12-04 02:05 UTC, 051198Hz commented on Data/Data/EditVideoRepository.swift
> +            let dto = try? JSONDecoder().decode(EditVideoDTO.self, from: data),
P1: 이게 성공 하나요..? CRDTElementSetState로 디코딩해야하지 않나요?

2024-12-04 02:05 UTC, 051198Hz commented on Data/Data/EditVideoRepository.swift
> +            let elementSet = await crdt.localAdd(element: element)
P1: 외부에서 전달받은 상태를 적용하기 위해서는 LWWElemetSetState를 merge해야 해요. 
localAdd는 로컬에서 일어난 편집을 저장하고, 이로부터 생성된 LWWElementSetState를 인코딩해서 외부에 전달해요.
CRDT 사용 방법을 다시 확인해주세요

2024-12-04 02:05 UTC, 051198Hz commented on Data/Data/DTO/EditVideoElement.swift
> +    let editingType: EditingType
P1: 같은 비디오인지만 editingType에 따라 다른 해시값을 가지게 돼서, 같은 동영상이지만 두개의 동영상이 생길 수 있을 것 같아요. 
editingType을 제거하고, 외부에서 어떤 변경이 일어났든 변경이 일어난 값만 인자로 받아 그것만 CRDT에서 add하는게 더 유연한 코드일 것 같아요

2024-12-04 02:09 UTC, jungseokyoung-cloud commented on Data/Data/EditVideoRepository.swift
> +        await crdt.merge(with: elementSet)
네넵 반영했습니다!

2024-12-04 02:09 UTC, jungseokyoung-cloud commented on Domain/Interfaces/UseCaseInterface/VideoUseCaseInterface.swift
반영하겠슴다

2024-12-04 02:11 UTC, jungseokyoung-cloud commented on Domain/UseCase/VideoUseCase.swift
> +    private let editVideoRepository: EditVideoRepositoryInterface
저번에 회의에서 논의되었던 내용 아니였나요?? UseCase에서 2가지 Interface를 채택하겠다고 했습니다. 
UseCase를 각각 가져가는게 아닌 공유 컨테이너 + Edit 이렇게요

2024-12-04 02:11 UTC, jungseokyoung-cloud commented on Domain/UseCase/VideoUseCase.swift
> +            .store(in: &cancellables)
이것 역시 위와 동일합니다.

2024-12-04 02:15 UTC, jungseokyoung-cloud commented on Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
> +    func reArrangingVideo(_ video: Video)
제가 생각했던 것은 편집된 내용을 전달 받는 것이긴 했습니다. 그렇다면 윤회님은 `trimmingVideo(url:startTime:endTime:)` 이런식으로 구체적으로 원하시는 건가요?

2024-12-04 02:18 UTC, jungseokyoung-cloud commented on Data/Data/DTO/EditVideoElement.swift
> +    let editingType: EditingType
이건 의도한 거긴합니다. 비디오 순서를 바꾸고 있는 것과 비디오 트리밍을 하는 것이 별도라고 생각했습니다. 
따라서, 별도의 해시값으로 관리하여, 별도의 이벤트로 관리하고자 했습니다.
 이건 다른분들의 의견도 궁금합니다.

2024-12-04 02:19 UTC, jungseokyoung-cloud commented on Data/Data/EditVideoRepository.swift
> +            let dto = try? JSONDecoder().decode(EditVideoDTO.self, from: data),
바로 밑에 element로 변환하는 코드 있습니다

2024-12-04 02:24 UTC, jungseokyoung-cloud commented on Data/Data/EditVideoRepository.swift
> +            let elementSet = await crdt.localAdd(element: element)
그렇다면 DTO에서 해당 정보가 필요하겠네요 이건 적용하겠슴다

2024-12-04 02:33 UTC, jungseokyoung-cloud commented on Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
> +    var reArrangingVideo: PassthroughSubject<[Video], Never> { get }
어허.. 이건 사실 전체를 반환한다 논의 되긴 했었었는데, trimingVideo관련된 부분 확정나면 같이 수정하겠습니다

2024-12-04 02:36 UTC, LURKS02 approved these changes
고생하셨습니다!

2024-12-04 02:36 UTC, LURKS02 commented on Domain/Entity/Video.swift
> +    public let endTime: Double
제가 생각한 방향은 석영님과 동일한데.. 존재하는 값을 수정하는게 아니라 갈아끼는 방향으로 생각했어요

2024-12-04 02:36 UTC, LURKS02 commented on Data/Data/DTO/EditVideoElement.swift
> +    let editingType: EditingType
editingType을 따로 가지게 하신 이유가 저도 궁금합니다. 저도 윤회님 말씀대로 생각했었거든요

2024-12-04 02:36 UTC, LURKS02 commented on Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
> +    var reArrangingVideo: PassthroughSubject<[Video], Never> { get }
P3: 저도 이 부분에 동의합니다!

2024-12-04 02:57 UTC, 051198Hz commented on Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
> +    func reArrangingVideo(_ video: Video)
넵!
그렇지 않으면 편집에 필요한 데이터(비디오 배열) 등을 뷰모델에서 가지고 있게 되고, 실제 편집 로직 또한 뷰모델에 있게 될 것 같아서요
물론 편집이 뷰(뷰컨, 뷰모델) 에서 이뤄지긴 하지만, 앱에서 운용할 실제 데이터의 편집은 유즈케이스에서 관리하는 것이 맞지 않나 하는 의견입니당,,

2024-12-04 03:00 UTC, 051198Hz commented on Domain/UseCase/VideoUseCase.swift
> +    private let editVideoRepository: EditVideoRepositoryInterface
피곤 이슈로 헛것을 봤슴니다~ 죄송함니다

2024-12-04 03:01 UTC, 051198Hz commented on Domain/UseCase/VideoUseCase.swift
> +            .store(in: &cancellables)
잠 깨고 오겠슴니다..

2024-12-04 05:21 UTC, around-forest commented on Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
> +    var reArrangingVideo: PassthroughSubject<[Video], Never> { get }
P3: 저도 편집된 비디오만 반환받는게 좋지 않을까 싶습니다!

2024-12-04 05:22 UTC, jungseokyoung-cloud commented on Domain/Interfaces/RepositoryInterface/EditVideoRepositoryInterface.swift
> +    var reArrangingVideo: PassthroughSubject<[Video], Never> { get }
반영했습니다

2024-12-04 05:22 UTC, jungseokyoung-cloud commented on Data/Data/DTO/EditVideoElement.swift
> +    let editingType: EditingType
반영해씀다

2024-12-04 05:25 UTC, around-forest commented on Data/Data/DTO/EditVideoElement.swift
> +    let editingType: EditingType
저도 type으로 구분하기보다는 하나의 영상에서 변경된 부분만 처리하게 하는게 좋지 않을까 생각됩니다!

2024-12-04 12:10 UTC, 051198Hz requested changes
고생 많으셨습니다~ 코멘트 하나만 확인 부탁드립니다!

2024-12-04 12:10 UTC, 051198Hz commented on Data/Data/EditVideoRepository.swift
> +        }
P1: 이부분 이렇게 바뀌어야할 것 같아요
```swift
let  elements = videos.map { DataMapper.mappingToEditVideoElement(
            $0,
            editor: socketProvider.displayName
        )}
let elementSetState = elementSet.localAdd(elements: elements)
guard let elementData = try? JSONEncoder().encode(elementSetState) else { return }

socketProvider.broadcast(data: elementData)

2024-12-04 12:18 UTC, jungseokyoung-cloud commented on Data/Data/EditVideoRepository.swift
> +        }
반영 완료했습니다!

2024-12-04 12:20 UTC, 051198Hz approved these changes
최고!

2024-12-04 12:27 UTC, LURKS02 approved these changes
고생하셨습니다! 승인해두었습니다.

2024-12-04 12:34 UTC, around-forest approved these changes
고생하셨습니다!

2024-12-04 12:35 UTC, merged