[Feature/#4]  레이더 형태로 주변 유저 목록을 표시하는 UI 설계
boostcampwm-2024/iOS09-BeStory pull request #9
Opened 2024-11-10 14:38 UTC by around-forest

## 관련 이슈

- [레이더 형태로 주변 유저 목록을 표시하는 UI 설계](https://github.com/boostcampwm-2024/iOS09-BeStory/issues/4)

## ✅ 완료 및 수정 내역

### UI 구현사항
- [x] ViewController & ViewModel 구현
- [x] 랜덤 위치에 캐릭터 생성 (캐릭터가 겹치지 않게 배치)
- [x] 모든 유저 캐릭터는 일단 랜덤 컬러 뷰로 구현 -> 랜덤 이모지
- [x] 다른 유저 캐릭터를 탭하여 그룹을 진행

### 로직 구현사항
- [x] 표시해야 할 유저들을 겹치지 않게 하는 로직

## 🛠️ 테스트 방법

- 석영님의 PR을 기준으로 ViewController와 ViewModel을 수정했습니다. 하지만, 실제로 구현한 기능이 동작하는 지에 대해서는 석영님 PR이 merge 됐을 때 함께 디바이스 테스트를 해야 합니다.

## 📝 리뷰 노트

### 참고 사항
크라켄에서 commit을 날릴 때 staging을 수동으로 해야하는지 몰랐습니다. ㅠㅠㅠㅠㅠㅠㅠ
push 하기 전 commit 에서 해당 사실을 알게되었고, 그래서 처음 몇 commit에 수정사항이 담기지 않았습니다... 죄송합니다. 
다음 PR 부터는 꼭 매 commit 마다 staging을 잘 적용하도록 하겠습니다.

### Fetch User -> View Update -> Updated User -> View Update의 흐름
처음 석영님의 UseCaseInterface를 확인한 뒤, browsingUser가 어떤 역할을 하는지 정확히 파악이 안됐습니다.
고민 끝에 제가 해석한 해당 프로퍼티의 역할과 UseCase 메서드들의 역할은 다음과 같습니다.

1. fetchBrowsingUsers: 처음 ViewController가 호출 됐을 때 호출하여 초기 주변 유저 목록을 가져오는 메서드
2. inviteUser: 사용자가 다른 사용자 캐릭터를 탭 했을 때, 그룹으로 묶기 위해 호출되는 메서드
3. browsingUser: 새로운 사용자 새로 추가되거나 기존 사용자가 lost 됐을 때 반응하는 프로퍼티

위에 따라, 다음과 같이 흐름을 수정했습니다.

1. ViewModel의 users 프로퍼티를 ViewController가 bind 하고, 
2. ViewModel이 UseCase의 browsingUser를 bind 한 뒤, 변화를 감지하여 새로운 유저가 추가됐을 때 users에 추가, 기존 유저가 lost 됐을 때 users의 해당 유저 state를 업데이트 하고,
3. ViewController가 users의 변화를 감지하여 view를 업데이트(found, lost에 따른 변화)

### ViewController에서의 View Update
고민이 많았던 부분입니다. 우선 결론만 말씀드리면, ViewModel의 users의 변화를 ViewController에서 감지했을 때, users에 있는 user를 하나씩 확인하여 추가된 유저라면 view를 추가, lost된 유저라면 view를 삭제하게끔 했습니다.

## 📱 스크린샷(선택)

<img width="305" alt="connection" src="https://github.com/user-attachments/assets/bab6c32f-fef5-4109-badc-0cf9b6cb7dfc">

2024-11-11 09:34 UTC, 051198Hz requested changes

2024-11-11 09:34 UTC, 051198Hz commented on Feature/Feature/ConnectionView/ConnectionViewController.swift
> +import Combine
알파벳 순으로 정렬 부탁드려여~

2024-11-11 09:34 UTC, 051198Hz commented on Feature/Feature/ConnectionView/ConnectionViewController.swift
> +}
UIAction 관련 내용 알아봐주세요!
objc사용에 대해서도 논의해봐야 겠네야

2024-11-11 09:34 UTC, 051198Hz commented on Feature/Feature/ConnectionView/ConnectionViewController.swift
> +                removeUserCircleView(position: currentPosition)
포지셔 검사 등의 로직은 뷰모델로 들어가고, 뷰모들엔 추가/삭제하는 유저에 대해서 값을 방출하고, 뷰는 추가/삭제 작업만 하도록 할 수 있을것 같네요~

2024-11-11 09:45 UTC, 051198Hz reviewed
고생 많으셨습니다!

2024-11-11 11:22 UTC, around-forest commented on Feature/Feature/ConnectionView/ConnectionViewController.swift
> +import Combine
확인했습니다!

2024-11-11 13:08 UTC, LURKS02 reviewed
고생하셨습니다!

2024-11-11 13:08 UTC, LURKS02 commented on Feature/Feature/ConnectionView/ViewModel/ViewModelable.swift
> +}
뷰모델 프로토콜 네이밍도 한 번 이야기해서 맞춰보면 좋을 것 같습니다!!

2024-11-11 13:08 UTC, LURKS02 commented on Feature/Feature/ConnectionView/ViewModel/ViewBindable.swift
> +}
이 프로토콜은 Output을 뷰에 바인드 해주는 역할인 것 같은데, OutputBindable이라는 이름이 더 적합해보입니다! (그리고 ViewBindable을 따로 구현해주신 이유가 궁금합니다!)

2024-11-11 13:22 UTC, around-forest commented on Feature/Feature/ConnectionView/ViewModel/ViewBindable.swift
> +}
Input-Output Pattern을 적용해볼 때 윤회님의 PR을 많이 참고했습니다. 

해당 PR에서 윤회님이 `ViewProtocol`을 구현하신걸 확인했을 때, View에 대한 protocol이 아닌 ViewModelable 처럼 Input-Output 그리고 binding에 대한 부분만 protocol을 구현하는건 어떨까? 하는 생각에 시도해봤습니다.

사실 처음에는 `associatedtype OutputError: Error`가 더 있고, 메서드도 `func handleError(_ error: OutputError)` 도 추가했었는데요, 필요한가? 라는 생각에 자꾸 빼내다 보니 저 부분만 남겨져 있습니다. (사실 저 상태면 없어도 될 듯 합니다)

결론은 음... 뷰 모델 프로토콜 네이밍과 이 부분에 대한 이야기를 나눠보고 싶었습니다!

2024-11-11 13:28 UTC, around-forest commented on Feature/Feature/ConnectionView/ConnectionViewController.swift
> +            if user.state == .found {
좋습니다! 아무래도 이 부분에 대해서는 공통으로 리뷰가 들어오네요 ㅠㅠ 
확실히 뷰를 더 멍청하게 만들도록 개선이 필요해 보입니다.
시도해보고, 개선이 되었다 싶으면 모두에게 말씀드리겠습니다!

2024-11-11 13:33 UTC, around-forest commented on Feature/Feature/ConnectionView/ConnectionViewController.swift
> +        userContainerView.setNeedsLayout()
가장 큰 차이는 setNeedsLayout은 다음 사이클에 실행되고, layoutIfNeeded는 바로 실행된다고 알고 있는데,
결국 반복문을 다 돌고 난 뒤 해당 부분에 레이아웃 갱신 코드가 들어가기 때문에 애니메이션이 들어가지 않는 이상 둘의 큰 차이가 없다 생각했습니다!
그래서 그럼 시스템에 알리고, 알아서 업데이트 하게 하는게 더 낫지 않을까 생각했습니다!

2024-11-11 13:38 UTC, around-forest commented on Feature/Feature/ConnectionView/ViewModel/ConnectionViewModel.swift
> +protocol ConnectionViewModelable: ViewModelable where
ViewModelable(가제) 같은 모든 뷰에서 사용가능한 공통 protocol을 구현하고,
각각에서 필요한대로 Input-Output을 구체화 하는건 어떨까 해서 한번 시도해봤습니다!

2024-11-12 00:59 UTC, 051198Hz approved these changes
성능적이나 제안 외에 동작을 위한 기능은 다 제공하는것으로 보여 승인 드립니다!

2024-11-13 12:27 UTC, closed without merging